"""auto

Revision ID: 6c7e97a3aa8a
Revises: 149167b7c03e
Create Date: 2021-11-23 23:07:49.227881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7e97a3aa8a'
down_revision = '149167b7c03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
